
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Servicename }}
spec:
  selector:
    pp.kubernetes.io/name: {{ .Values.selector.name }}
  type: NodePort
  ports:
  - name: port-message
    protocol: TCP
    port: 8080