
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Servicename }}
spec:
  selector:
    {{- toYaml .Values.selector | nindent 4 }}
  type: NodePort
  ports:
  - name: port-message
    protocol: TCP
    port: 8080